[template.environment]
  REACT_APP_CLIENT_ID = "EPCC Client ID"
  REACT_APP_STRIPE_KEY = "Stripe Publishable Key"
  REACT_APP_ALGOLIA_APP_ID =  "Algolia App ID"
  REACT_APP_ALGOLIA_API_KEY = "Algolia API Key"
  REACT_APP_ALGOLIA_INDEX_NAME = "Algolia Index Name"